### ISSUE TITLE
Hostedpage new subscription?

### ISSUE THREAD

**Issue by orsing** [teference/zoho-dotnet#1]
I may be missing something, but how can one get the hosted page for a new subscription? 
There is HostedPage.UpdateSubscriptionAsync and HostedPage.UpdateCardAsync, but nothing for new subscription (or buy one time addon).
Thanks!

**Comment by jsinh** [comment]
Hello @orsing 

You spot it right, as I mentioned in README.md - this library is not complete and WIP at the moment. I have only imported or implemented the API fragments that I need for immediate use for myself.

But again, I wish it can be useful for everyone like me seeking a simple .NET SDK to access Zoho Sub. API. The HostedPage section is missing two fragments - "Create a subscription" & "Buy one-time addon for a subscription".

I will work on it this week and push an update once done. Hope that helps, glad to know you consuming this little side effort I made :)

Feel free to open issue if you find any bug or need more missing fragments from API.

**Comment by jsinh** [comment]
@orsing 

Pushed what you asked for:
https://github.com/teference/zoho-dotnet/releases/tag/v0.6.13
https://www.nuget.org/packages/Zoho.Api/0.6.13

Only ran few primary tests, but should work. Ping if that is not the case with some sample data that fails!
Hope that helps, cheers!
