### ISSUE TITLE
Getting Started?

### ISSUE THREAD

**Issue by schenckg** [teference/zoho-dotnet#11]
Hello,

First, does this code support the new Zoho V2 API?

Assuming so I'm having trouble getting started.  Do you have a basic example that shows the steps needed to authenticate with the OAuth methods and then make at least one request with the tokens?  I can't seem to figure out how I'm supposed to use the code...

Thanks!

**Comment by jsinh** [comment]
Hello @schenckg 

Thanks for reaching out. Unfortunately, follow library is build to work against V1 of API.
Here is the details of it: https://github.com/teference/zoho-dotnet/blob/master/source/Zoho.Api/ZohoConfig.cs#L8

In case you wish to still use it, you can generate a token in your zoho account and use the organization id and token to make calls using this API.

A simple initialization is shown here. 
https://github.com/teference/zoho-dotnet/blob/master/test/Zoho.ApiTest/Program.cs#L18-L23
Once initialized you can use the `zohoClient` object to make API calls.

Hope this helps!
