### ISSUE TITLE
Timeout after two 204 resulting queries

### ISSUE THREAD

**Issue by schenckg** [teference/zoho-dotnet#12]
If I use the ZCRMModule.SearchByPhone() on Leads (although issues regardless of entity type) with a number that doesn't match any records then I get a 204 results which is expected.  However if I make the same query two more times, the second time it fails with again with a 204 (expected) but the third time it times out after 40 seconds.  This does not seem to be an issues with the REST API itself as invoking the phone search from postman works fine regardless of how many times.  Note that doing a search which returns results does not result in any eventual query problem.

**Comment by jsinh** [comment]
@schenckg - Thanks for reaching out.
I think you are posting a bug on the wrong repo. This SDK or NuGET only contains API calls for Zoho Subscription.
