### ISSUE TITLE
Wiki not available on this page

### ISSUE THREAD

**Issue by NeilMcKLogic** [teference/zoho-dotnet#17]
Hi, the readme for this project says :

Further details on how to use / integrate Zoho.Api packages please refer this repository wiki pages.
Zoho API .NET SDK WIKI

...but clicking on that link just brings me back tot he same page (the Code tab). When I click the Wiki tab at the top of the page, it also brings me back to the Code tab/page. So I cannot get to the Wiki to get to the details on how to use / integration Zoho.Api packages.

Help please ?
Neil

**Comment by jsinh** [comment]
Hey @NeilMcKechnie  - thanks for reaching out.
I haven't created any WIKI or doc for it at the moment actually, that is why the redirects are broken, sorry if that is misleading.

The SDK for this API is pretty straightforward, I will schedule to do a sample snippet or "getting started" guide soon (no concrete promises on a date for now but soon :D )

For now, to un-stuck, you here is a very basic sample I use while I need to develop or test things
URL: https://github.com/teference/zoho-dotnet/blob/master/test/Zoho.ApiTest/Program.cs#L18-L23

This demonstrates the initialization part.
then you can explore/consume the API methods at:

```
zohoClient.Subscription.*.*()
```

Cheers!
