### ISSUE TITLE
How to Get AuthToken and OrganizationId once initialize api ?

### ISSUE THREAD

**Issue by HusseinElGanzory** [teference/zoho-dotnet#18]

**Comment by jsinh** [comment]
Hello Hussein,

Not completely sure what you mean to ask there or why you need to get AuthToken and OrganizationId 
after initialization but those are stored in the following property:

https://github.com/teference/zoho-dotnet/blob/master/source/Zoho.Api/ZohoClient.cs#L28

Hope that helps, thanks

**Comment by HusseinElGanzory** [comment]
organizationId & AuthCode Always Fixed . not changed for every request ? where i can get AuthToken?

**Comment by jsinh** [comment]
@HusseinElGanzory - If you want to keep changing those values - then create a new instance.
But for that particular instance, it does not change unless you do.

Not sure what you mean by "Where I can get AuthToken?" - if you mean how can you generate one then it would be in Zoho - you can refer to their documents for it - or ask in support depending on your privileges and user setup

**Comment by HusseinElGanzory** [comment]
i had another question please. zoho.api support create invoices if not any sample for it

**Comment by jsinh** [comment]
@HusseinElGanzory It does not create invoices.
This NuGet package is only translating following API endpoints: 
https://www.zoho.com/subscriptions/api/v1/#introduction

So those can be called from C# and .NET in a more elegant way.
