### ISSUE TITLE
sand

### ISSUE THREAD

**Issue by wazahuis** [teference/zoho-dotnet#19]
I've trying to use the API with the sandbox.   Just wondering though is this API using the v2 API or V1?

**Comment by jsinh** [comment]
@wazahuis  Thanks for reaching out. This API wrapper is using V1 API.

There was no concept of sandbox when I started this wrapper work.
https://github.com/teference/zoho-dotnet/blob/master/source/Zoho.Api/ZohoConfig.cs#L4-L8
