### ISSUE TITLE
Service Location US vs EU

### ISSUE THREAD

**Issue by kruijs** [teference/zoho-dotnet#3]
ZOHO uses different API endpoints for US and EU customers. Currently, this information is stored in the ApiResource resx (ZsRootEndpoint).

It would be great if there was a possibility to set the URL or to have a switch property on the configuration object.

https://subscriptions.zoho.**com**/api/v1/
https://subscriptions.zoho.**eu**/api/v1/

**Comment by jsinh** [comment]
@kruijs - thanks for pointing this out, would have never know about the location specific API base URL

I have commit some changes to accommodate this spec, will take a second look at it and push a NuGet soon.

**Comment by kruijs** [comment]
That's great. Thanks a lot for your efforts.

**Comment by jsinh** [comment]
Pushed option to set API Base URL (do not forget to end with '/'

[Release Note](https://github.com/teference/zoho-dotnet/releases/tag/v0.6.15)
[Nuget v0.6.15](https://www.nuget.org/packages/Zoho.Api/0.6.15)

Pardon on late response
