### ISSUE TITLE
Error parsing HostedPage response

### ISSUE THREAD

**Issue by kruijs** [teference/zoho-dotnet#4]
The ZsHostedPageData class Property "Invoice" should be of type ZsInvoice intead of string, as this:

public sealed class ZsHostedPageData
    {
        [JsonProperty("subscription")]
        public ZsSubscription Subscription { get; set; }
        [JsonProperty("invoice")]
        public ZsInvoice Invoice { get; set; }
    }

**Comment by jsinh** [comment]
Agreed, at the time of writing this piece I might have ignored i guess.

At the moment if i compare the Zoho Documentation for sample response JSON (invoice section) it is somewhat evolved from the last time I used it as reference to create ZsInvoice

Zoho guys are not so good at maintaining / updating and intimating about the doc / API changes.

I will have to take time and re-write ZsInvoice and others after a fresh compare but for now I have changed the "Invoice" property from String to ZsInvoice (hope that helps)

[Release Note](https://github.com/teference/zoho-dotnet/releases/tag/v0.6.15)
[Nuget v0.6.15](https://www.nuget.org/packages/Zoho.Api/0.6.15)

Pardon on late response
