### ISSUE TITLE
Wiki URL broken

### ISSUE THREAD

**Issue by elunap** [teference/zoho-dotnet#6]
Can you fix the url:

https://github.com/teference/zoho-dotnet/wiki

I can't see the documentation because of that.

Thanks.

**Comment by jsinh** [comment]
Hey @elunap  - thanks for reaching out.
I haven't created any WIKI or doc for it at the moment actually, that is why it points to a blank page.

The SDK for this API is pretty straightforward, I will schedule to do a sample snippet or "getting started" guide soon (no concrete promises on date for now but soon :D )

For now, to un-stuck you, here is a very basic sample I use while I need to develop or test things
URL: https://github.com/teference/zoho-dotnet/blob/master/test/Zoho.ApiTest/Program.cs#L18-L23

This demonstrates initialization part.
then you can explore/consume the API methods at:
```
zohoClient.Subscription.*.*()
```
Cheers!

**Comment by elunap** [comment]
Thanks a lot! I really appreciate it.
